### ISSUE TITLE
Quelque commentaires

### ISSUE THREAD

**Issue by dmathieu** [kevin-verschaeve/ember-echecs#1]
C'est intéressant. Mais j'arrive pas a bouger de pions avec ma souris, est-ce normal?
Globalement, le probleme est assez similaire a celui des autres, vous tentez de modifier directement le dom, alors qu'il serait beaucoup plus efficient d'utiliser les bindings d'ember.

Dans votre cas par exemple, chaque piece pourrait etre un [component](http://emberjs.com/api/classes/Ember.Component.html). Vous les positionnez sur l'échiquier, puis pouvez gérer le drag/drop [directement dans l'élément](http://nepalonrails.com/blog/2014/02/drag-and-drop-with-emberjs), sans avoir a manipuler d'objet du dom, mais en laissant faire ember.

En dehors de ca,
![](http://ct.fra.bz/ol/fz/sw/i57/2/11/16/frabz-well-done-young-man-98da4e.jpg)

**Comment by kevin-verschaeve** [comment]
Pour déplacer un pion, il faut cliquer dessus pour voir les cases où il peut se déplacer en surbrillance. Ensuite il faut cliquer sur une de ces cases et le pion devrait changer de place.

OK pour les bindings et les components, je vais regarder ca et voir ce que je peut essayer de faire.

Merci !
